name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        arch: [x86, arm32, arm64]
        compiler: [llvm-9, llvm-10, llvm-11]

        include:
          - arch: x86
            compiler: gcc-7
          - arch: x86
            compiler: gcc-8
          - arch: x86
            compiler: gcc-9
          - arch: x86
            compiler: gcc-10

          - arch: x86
            compiler: clang-9
          - arch: x86
            compiler: clang-10
          - arch: x86
            compiler: clang-11

          - arch: arm32
            compiler: gcc-arm-linux-gnueabihf
          - arch: arm64
            compiler: gcc-aarch64-linux-gnu

    runs-on: ubuntu-latest

    steps:
    - name: Install
      run: |
        c=${{matrix.compiler}}
        v=${c##llvm-}
        case $c in
            # Need all {llvm,clang,lld}-$v packages
            llvm-*) EXTRA="clang-${v} lld-${v}" ;;
        esac

        sudo apt-get update -q
        sudo apt-get install -y build-essential python3 ${{matrix.compiler}} ${EXTRA}

    - uses: actions/checkout@v2

    - name: Build
      run: |
        a=${{matrix.arch}}
        c=${{matrix.compiler}}

        # Select appropriate CROSS_COMPILE for non-x86 targets
        case $a in
            arm32) CROSS="CROSS_COMPILE=arm-linux-gnueabihf-" ;;
            arm64) CROSS="CROSS_COMPILE=aarch64-linux-gnu-"   ;;
        esac

        # Select appropriate LLVM= or CC=
        case $c in
            llvm-*)  COMP="LLVM=${c#llvm}" ;;
            *) [[ -z "$CROSS" ]] && COMP="CC=$c" ;;
        esac

        make -j`nproc` ARCH=$a $CROSS $COMP
